/*
 * This file was automatically generated by EvoSuite
 * Sun Feb 17 07:52:17 GMT 2019
 */

package org.sat4j.minisat.orders;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.sat4j.minisat.constraints.cnf.Lits;
import org.sat4j.minisat.orders.SubsetVarOrder;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SubsetVarOrder_ESTest extends SubsetVarOrder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Lits lits0 = new Lits();
      int[] intArray0 = new int[6];
      intArray0[0] = 2269;
      intArray0[1] = 3;
      intArray0[2] = (-4);
      lits0.getFromPool(2269);
      SubsetVarOrder subsetVarOrder0 = new SubsetVarOrder(intArray0);
      subsetVarOrder0.setLits(lits0);
      // Undeclared exception!
      try { 
        subsetVarOrder0.init();
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      int[] intArray0 = new int[2];
      SubsetVarOrder subsetVarOrder0 = new SubsetVarOrder(intArray0);
      Lits lits0 = new Lits();
      double[] doubleArray0 = new double[8];
      subsetVarOrder0.activity = doubleArray0;
      subsetVarOrder0.setLits(lits0);
      // Undeclared exception!
      try { 
        subsetVarOrder0.init();
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      int[] intArray0 = new int[0];
      SubsetVarOrder subsetVarOrder0 = new SubsetVarOrder(intArray0);
      // Undeclared exception!
      try { 
        subsetVarOrder0.undo(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.sat4j.minisat.orders.SubsetVarOrder", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      int[] intArray0 = new int[0];
      Lits lits0 = new Lits();
      SubsetVarOrder subsetVarOrder0 = new SubsetVarOrder(intArray0);
      subsetVarOrder0.setLits(lits0);
      subsetVarOrder0.init();
      // Undeclared exception!
      try { 
        subsetVarOrder0.undo(4);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 4
         //
         verifyException("org.sat4j.minisat.orders.SubsetVarOrder", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      int[] intArray0 = new int[0];
      Lits lits0 = new Lits();
      SubsetVarOrder subsetVarOrder0 = new SubsetVarOrder(intArray0);
      lits0.ensurePool(5550);
      subsetVarOrder0.setLits(lits0);
      subsetVarOrder0.init();
      // Undeclared exception!
      subsetVarOrder0.init();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int[] intArray0 = new int[6];
      SubsetVarOrder subsetVarOrder0 = new SubsetVarOrder(intArray0);
      // Undeclared exception!
      try { 
        subsetVarOrder0.init();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.sat4j.minisat.orders.SubsetVarOrder", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SubsetVarOrder subsetVarOrder0 = null;
      try {
        subsetVarOrder0 = new SubsetVarOrder((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.sat4j.minisat.orders.SubsetVarOrder", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int[] intArray0 = new int[0];
      Lits lits0 = new Lits();
      SubsetVarOrder subsetVarOrder0 = new SubsetVarOrder(intArray0);
      subsetVarOrder0.setLits(lits0);
      subsetVarOrder0.init();
      subsetVarOrder0.undo(0);
      assertEquals(0, subsetVarOrder0.numberOfInterestingVariables());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Lits lits0 = new Lits();
      int[] intArray0 = new int[1];
      intArray0[0] = 212;
      lits0.getFromPool(212);
      SubsetVarOrder subsetVarOrder0 = new SubsetVarOrder(intArray0);
      subsetVarOrder0.setLits(lits0);
      subsetVarOrder0.init();
      subsetVarOrder0.undo(212);
      assertEquals(0, subsetVarOrder0.numberOfInterestingVariables());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Lits lits0 = new Lits();
      int[] intArray0 = new int[5];
      intArray0[0] = 159;
      SubsetVarOrder subsetVarOrder0 = new SubsetVarOrder(intArray0);
      subsetVarOrder0.setLits(lits0);
      // Undeclared exception!
      try { 
        subsetVarOrder0.init();
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // 0/159
         //
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Lits lits0 = new Lits();
      int[] intArray0 = new int[1];
      intArray0[0] = 212;
      lits0.ensurePool(212);
      SubsetVarOrder subsetVarOrder0 = new SubsetVarOrder(intArray0);
      subsetVarOrder0.setLits(lits0);
      subsetVarOrder0.init();
      subsetVarOrder0.undo(212);
      assertEquals(0, subsetVarOrder0.numberOfInterestingVariables());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Lits lits0 = new Lits();
      int[] intArray0 = new int[15];
      SubsetVarOrder subsetVarOrder0 = new SubsetVarOrder(intArray0);
      subsetVarOrder0.activity = null;
      subsetVarOrder0.setLits(lits0);
      // Undeclared exception!
      try { 
        subsetVarOrder0.init();
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
